# Generated by Django 3.2 on 2021-05-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duyuru_basligi', models.CharField(max_length=32, verbose_name='Duyuru Başlığı')),
                ('duyuru_metni', models.CharField(max_length=256, verbose_name='Duyuru Metni')),
                ('guncelleme_tarihi', models.DateField(default='2021-05-30', editable=False, verbose_name='Yayınlanma Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Duyuru',
            },
        ),
    ]
