# Generated by Django 3.2 on 2021-05-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duyurular', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyuru',
            name='duyuru_metni',
            field=models.TextField(max_length=256, verbose_name='Duyuru Metni'),
        ),
    ]
