# Generated by Django 3.2 on 2021-05-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duyuru_baslik', models.CharField(max_length=32, verbose_name='Duyuru Başlığı')),
                ('duyuru_text', models.TextField(verbose_name='Duyuru Metni')),
                ('duyuru_arkaplan_resmi', models.URLField(default='https://www.akisaluminyum.com.tr/assets/filter/img/407604122west_gate_banner.jpg', help_text="Arkaplanda gözükmesini istediğiniz resme ait URL'yi girin.", verbose_name='Duyuru Arkaplan Resmi')),
                ('duyuru_kenar_karartma_renkkodu', models.CharField(default='#ffffff', help_text='HEX Kodu olarak giriniz.', max_length=8, verbose_name='Kenar Karartma Rengi')),
                ('duyuru_yayinlanma_tarihi', models.DateField(default='2021-05-29')),
            ],
            options={
                'verbose_name_plural': 'Ana Sayfa Duyuru',
            },
        ),
    ]
