# Generated by Django 3.2 on 2021-05-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genel', '0002_alter_duyuru_duyuru_yayinlanma_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyuru',
            name='duyuru_yayinlanma_tarihi',
            field=models.DateField(default='2021-05-29', editable=False),
        ),
    ]
