# Generated by Django 3.2 on 2021-05-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genel', '0003_alter_duyuru_duyuru_yayinlanma_tarihi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duyuru',
            name='duyuru_kenar_karartma_renkkodu',
        ),
    ]
