# Generated by Django 3.2 on 2021-05-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genel', '0007_alter_adres_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefonlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yonetim_tel', models.TextField(verbose_name='Yönetim Telefon')),
                ('muhasebe_tel', models.TextField(verbose_name='Muhasebe Telefon')),
                ('halklailiskiler_tel', models.TextField(verbose_name='Halkla İlişkiler Telefon')),
                ('a_resep_tel', models.TextField(verbose_name='A Resepsiyon Telefon')),
                ('b_resep_tel', models.TextField(verbose_name='B Resepsiyon Telefon')),
                ('c_resep_tel', models.TextField(verbose_name='C Resepsiyon Telefon')),
            ],
            options={
                'verbose_name_plural': 'Telefon Bilgileri',
            },
        ),
        migrations.AlterField(
            model_name='adres',
            name='adres',
            field=models.TextField(default='Konutkent, Dumlupınar Blv. No:391, 06810 Çankaya/Ankara', verbose_name='West-Gate Adres'),
        ),
    ]
