# Generated by Django 3.2 on 2021-05-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genel', '0008_auto_20210529_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yonetim_mail', models.CharField(max_length=32, verbose_name='Yönetim E-Mail')),
                ('muhasebe_mail', models.CharField(max_length=32, verbose_name='Muhasebe E-Mail')),
                ('halklailiskiler_mail', models.CharField(max_length=32, verbose_name='Halkla İlişkiler E-Mail')),
            ],
            options={
                'verbose_name_plural': 'E-Mail Bilgileri',
            },
        ),
        migrations.AlterField(
            model_name='telefonlar',
            name='a_resep_tel',
            field=models.CharField(blank=True, help_text='Bu alan boş bırakılabilir.', max_length=32, verbose_name='A Resepsiyon Telefon'),
        ),
        migrations.AlterField(
            model_name='telefonlar',
            name='b_resep_tel',
            field=models.CharField(blank=True, help_text='Bu alan boş bırakılabilir.', max_length=32, verbose_name='B Resepsiyon Telefon'),
        ),
        migrations.AlterField(
            model_name='telefonlar',
            name='c_resep_tel',
            field=models.CharField(blank=True, help_text='Bu alan boş bırakılabilir.', max_length=32, verbose_name='C Resepsiyon Telefon'),
        ),
        migrations.AlterField(
            model_name='telefonlar',
            name='halklailiskiler_tel',
            field=models.CharField(max_length=32, verbose_name='Halkla İlişkiler Telefon'),
        ),
        migrations.AlterField(
            model_name='telefonlar',
            name='muhasebe_tel',
            field=models.CharField(max_length=32, verbose_name='Muhasebe Telefon'),
        ),
        migrations.AlterField(
            model_name='telefonlar',
            name='yonetim_tel',
            field=models.CharField(max_length=32, verbose_name='Yönetim Telefon'),
        ),
    ]
