# Generated by Django 3.2 on 2021-05-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genel', '0009_auto_20210529_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaHakkimizda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ana_hakkimizda', models.TextField(help_text="Bu bölüm 'Ana Sayfa'nızın sol alt köşesinde görünür.", max_length=256, verbose_name='Hakkımızda')),
            ],
            options={
                'verbose_name_plural': 'Hakkımızda',
            },
        ),
    ]
