# Generated by Django 3.2 on 2021-05-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genel', '0010_anahakkimizda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosyalmedya',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Yönlendirilmesini istediğiniz telefon numarasını giriniz.', max_length=32, verbose_name='Whatsapp'),
        ),
    ]
