# Generated by Django 3.2 on 2021-05-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genel', '0011_alter_sosyalmedya_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosyalmedya',
            name='google',
            field=models.CharField(blank=True, max_length=128, verbose_name='Google+'),
        ),
    ]
