# Generated by Django 3.2 on 2021-05-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genel', '0012_alter_sosyalmedya_google'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sloganlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(help_text='Bu alan üst sol bölümde, bilgilendirme veya uyarı amacıyla kullanılabilir mesajlar bırakmanızı sağlar.', max_length=64, verbose_name='Mesajınız')),
                ('guncelleme_tarihi', models.DateField(default='2021-05-29', editable=False, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name_plural': 'Üst Mesajlar',
            },
        ),
        migrations.AddField(
            model_name='anahakkimizda',
            name='guncelleme_tarihi',
            field=models.DateField(default='2021-05-29', editable=False, verbose_name='Son Güncelleme'),
        ),
        migrations.AddField(
            model_name='mailler',
            name='guncelleme_tarihi',
            field=models.DateField(default='2021-05-29', editable=False, verbose_name='Son Güncelleme'),
        ),
        migrations.AlterField(
            model_name='sosyalmedya',
            name='facebook',
            field=models.URLField(blank=True, help_text='Yönlendirilmesini istediğiniz facebook profil adresini girin.', verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='sosyalmedya',
            name='google',
            field=models.CharField(blank=True, help_text='Yönlendirilmesini istediğiniz mail adresini girin.', max_length=128, verbose_name='Google+'),
        ),
        migrations.AlterField(
            model_name='sosyalmedya',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Yönlendirilmesini istediğiniz linkedin profil adresini girin.', verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='sosyalmedya',
            name='pinterest',
            field=models.URLField(blank=True, help_text='Yönlendirilmesini istediğiniz pinterest adresini girin.', verbose_name='Pinterest'),
        ),
        migrations.AlterField(
            model_name='sosyalmedya',
            name='rss',
            field=models.URLField(blank=True, help_text='Yönlendirilmesini istediğiniz rss adresini girin.', verbose_name='Rss'),
        ),
        migrations.AlterField(
            model_name='sosyalmedya',
            name='twitter',
            field=models.URLField(blank=True, help_text='Yönlendirilmesini istediğiniz twitter profil adresini girin.', verbose_name='Twitter'),
        ),
    ]
