# Generated by Django 3.2 on 2021-05-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genel', '0013_auto_20210529_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefonlar',
            name='guncelleme_tarihi',
            field=models.DateField(default='2021-05-29', editable=False, verbose_name='Son Güncelleme'),
        ),
    ]
