# Generated by Django 3.2 on 2021-05-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genel', '0014_telefonlar_guncelleme_tarihi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Önerilen Boyutlar: 150x50 (Daha büyük boyutlar sayfa üst bölgesinde kaymalara sebep olabilir.)', upload_to='', verbose_name='Logo')),
                ('tik', models.CharField(default='Değiştirmek için dokunun', editable=False, max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Logo',
            },
        ),
    ]
