# Generated by Django 3.2 on 2021-05-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genel', '0015_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='tik',
            new_name='islem',
        ),
    ]
