# Generated by Django 3.2 on 2021-05-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genel', '0017_auto_20210529_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyukresimbilgilendirme',
            name='buton_txt',
            field=models.CharField(blank=True, help_text='Buton görünmesini istemiyorsanız boş bırakabilirsiniz.', max_length=24, verbose_name='Buton Yazısı'),
        ),
        migrations.AlterField(
            model_name='buyukresimbilgilendirme',
            name='buton_url',
            field=models.URLField(blank=True, help_text='Butona tıklanıldığında gidilmesini istediğiniz adresi giriniz.', verbose_name='Buton Yönlendirdiği Link'),
        ),
        migrations.AlterField(
            model_name='sloganlar',
            name='slogan',
            field=models.CharField(help_text='Bu alan üst sol bölümde, bilgilendirme veya uyarı amacıyla kullanılabilir mesajlar bırakmanızı sağlar.', max_length=128, verbose_name='Mesajınız'),
        ),
    ]
