# Generated by Django 3.2 on 2021-05-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genel', '0021_alter_sloganlar_slogan'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramGaleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='', verbose_name='Resim')),
                ('resim_url', models.URLField(verbose_name='Resim Instagram Linki')),
                ('eklenme_tarihi', models.DateField(default='2021-05-29', editable=False, verbose_name='Eklenme Tarihi')),
                ('islem', models.CharField(default='Düzenle', editable=False, max_length=32, verbose_name='Hızlı İşlem')),
            ],
            options={
                'verbose_name_plural': 'Instagram Galerisi',
            },
        ),
    ]
