# Generated by Django 3.2 on 2021-05-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genel', '0022_instagramgaleri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anahakkimizda',
            name='guncelleme_tarihi',
            field=models.DateField(default='2021-05-30', editable=False, verbose_name='Son Güncelleme'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='duyuru_yayinlanma_tarihi',
            field=models.DateField(default='2021-05-30', editable=False),
        ),
        migrations.AlterField(
            model_name='instagramgaleri',
            name='eklenme_tarihi',
            field=models.DateField(default='2021-05-30', editable=False, verbose_name='Eklenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='mailler',
            name='guncelleme_tarihi',
            field=models.DateField(default='2021-05-30', editable=False, verbose_name='Son Güncelleme'),
        ),
        migrations.AlterField(
            model_name='sloganlar',
            name='guncelleme_tarihi',
            field=models.DateField(default='2021-05-30', editable=False, verbose_name='Son Güncelleme'),
        ),
        migrations.AlterField(
            model_name='telefonlar',
            name='guncelleme_tarihi',
            field=models.DateField(default='2021-05-30', editable=False, verbose_name='Son Güncelleme'),
        ),
    ]
