# Generated by Django 3.2 on 2021-05-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genel', '0023_auto_20210530_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyukresimbilgilendirme',
            name='islem',
            field=models.CharField(default='Değiştirmek için dokunun', editable=False, max_length=32, verbose_name='Hızlı İşlem'),
        ),
    ]
