# Generated by Django 3.2 on 2021-05-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsm', models.ImageField(upload_to='', verbose_name='Resim')),
                ('guncelleme_tarihi', models.DateField(default='2021-05-30', editable=False, verbose_name='Yayınlanma Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Galeri',
            },
        ),
    ]
