# Generated by Django 3.2 on 2021-05-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0002_galeri_islem'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeri',
            name='aciklama',
            field=models.TextField(default='.', max_length=128, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='galeri',
            name='baslik',
            field=models.CharField(default='.', max_length=64, verbose_name='Resim Başlığı'),
        ),
    ]
