# Generated by Django 3.2 on 2021-05-30 16:48

from django.db import migrations, models
import galeri.validators


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0003_auto_20210530_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeri',
            name='video',
            field=models.FileField(default='.mp4', upload_to='', validators=[galeri.validators.validate_file_extension], verbose_name='Video'),
        ),
    ]
