# Generated by Django 3.2 on 2021-05-30 16:51

from django.db import migrations, models
import galeri.validators


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0004_galeri_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(default='.mp4', upload_to='', validators=[galeri.validators.validate_file_extension], verbose_name='Video')),
                ('guncelleme_tarihi', models.DateField(default='2021-05-30', editable=False, verbose_name='Yayınlanma Tarihi')),
                ('islem', models.CharField(default='Değiştirmek için dokunun', editable=False, max_length=32, verbose_name='Hızlı İşlem')),
            ],
            options={
                'verbose_name_plural': 'Video',
            },
        ),
        migrations.AlterModelOptions(
            name='galeri',
            options={'verbose_name_plural': 'Resim'},
        ),
        migrations.RemoveField(
            model_name='galeri',
            name='video',
        ),
    ]
