# Generated by Django 3.2 on 2021-05-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0005_auto_20210530_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='galerivideo',
            name='alt_baslik',
            field=models.CharField(default='.', max_length=256, verbose_name='Video Alt Yazı'),
        ),
        migrations.AddField(
            model_name='galerivideo',
            name='baslik',
            field=models.CharField(default='.', max_length=64, verbose_name='Video Başlığı'),
        ),
        migrations.AddField(
            model_name='galerivideo',
            name='orta_baslik',
            field=models.CharField(default='.', max_length=128, verbose_name='Video Orta Yazı'),
        ),
    ]
