# Generated by Django 3.2 on 2021-05-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0007_auto_20210530_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='galerivideo',
            name='kaydirma_rsm',
            field=models.ImageField(default='', upload_to='', verbose_name='Kaydırma Resmi'),
        ),
        migrations.AlterField(
            model_name='galeri',
            name='aciklama',
            field=models.TextField(max_length=128, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='galeri',
            name='baslik',
            field=models.CharField(max_length=64, verbose_name='Resim Başlığı'),
        ),
        migrations.AlterField(
            model_name='galerivideo',
            name='alt_baslik',
            field=models.CharField(blank=True, default=' ', max_length=256, verbose_name='Video Alt Yazı'),
        ),
        migrations.AlterField(
            model_name='galerivideo',
            name='baslik',
            field=models.CharField(blank=True, default='West Gate', max_length=64, verbose_name='Video Başlığı'),
        ),
        migrations.AlterField(
            model_name='galerivideo',
            name='orta_baslik',
            field=models.CharField(blank=True, default=' ', max_length=128, verbose_name='Video Orta Yazı'),
        ),
    ]
