# Generated by Django 3.2 on 2021-05-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0008_auto_20210530_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerivideo',
            name='islem',
            field=models.CharField(default='Düzenle', editable=False, max_length=32, verbose_name='Hızlı İşlem'),
        ),
    ]
