# Generated by Django 3.2 on 2021-05-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UstBolum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=32, verbose_name='Başlık')),
                ('ilk_parag', models.CharField(max_length=1024, verbose_name='İlk Paragraf')),
                ('ikinci_parag', models.CharField(help_text='2. paragraf eklemek istiyorsanız burayı doldurun.', max_length=256, verbose_name='İkinci Paragraf')),
                ('guncelleme_tarihi', models.DateField(default='2021-05-30', editable=False, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name_plural': 'Üst Bölüm',
            },
        ),
    ]
