# Generated by Django 3.2 on 2021-05-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakkimizda', '0002_auto_20210530_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='YanBuyukResim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsm', models.ImageField(upload_to='', verbose_name='Yan Resim')),
                ('guncelleme_tarihi', models.DateField(default='2021-05-30', editable=False, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name_plural': 'Yan Büyük Resim',
            },
        ),
    ]
