# Generated by Django 3.2 on 2021-05-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakkimizda', '0003_yanbuyukresim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altkutucuk',
            name='kutu_basligi',
            field=models.CharField(max_length=32, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='altkutucuk',
            name='kutu_icerigi',
            field=models.TextField(max_length=256, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='ustbolum',
            name='ikinci_parag',
            field=models.TextField(blank=True, help_text='2. paragraf eklemek istiyorsanız burayı doldurun.', max_length=1024, verbose_name='İkinci Paragraf'),
        ),
    ]
